### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by thanasipantazides**
**I will edit more documentation into this!**

#### `Listener`
- Handles interface with Formatter and logging.
- Can run as separate process from GSE.
- Receives uplink commands (to forward to Formatter) from GSE using Unix Datagram socket.
- Instantiates parser from `foxsi4-commands/systems.json` fields.

```mermaid
    flowchart LR
        formatter["Formatter"]
        listener["Listener"]
        logs["Log files"]
        gse["GSE"]
        formatter--raw data-->listener
        listener--raw frames-->logs
        listener--commands-->formatter
        gse--commands-->listener
        logs--raw frames-->gse
```

#### `PowerMonitorView`
- A widget for checking and setting onboard power state.
- Sends power commands through new `Listener` interface.
- Needs more in the backend to actually ingest data to display (see addition below).

#### `Singleton`
- A metaclass (I think?) for creating singleton classes.
- Used for `SystemConfiguration` and `FormatterUDPInterface`.

### Additions before close
- [ ] Parser backend support for power-related data.
- [ ] Docstrings in `PowerMonitorView`

#### `Listener` exit behavior
Currently, `Listener` (which does all raw data logging to file) is started in a child process from `FormatterUDPInterface` using [`QProcess()`](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QProcess.html#qprocess). When using `QProcess()`, `Listener` stops running when the GSE is quit. This is handy for debugging, because I don't need to find the background process ID for `Listener` and manually kill it every time I stop running the main GSE.

I also tried using [`subprocess`](https://docs.python.org/3/library/subprocess.html) for this, which does not terminate the background `Listener` process when the GSE is quit. Because `subprocess` has the functionality to terminate a process (using `Popen.terminate()` or `Popen.kill()` I included a property: `FormatterUDPInterface.end_background_process_on_close` which I check in the `__del__()` method of `FormatterUDPInterface` and conditionally terminate the `Listener` process. BUT! I now know `__del__()` is [never guaranteed to be called](https://docs.python.org/3/reference/datamodel.html#object.__del__), and as I have implemented things, `FormatterUDPInterface.__del__()` seems to be guaranteed _not_ to be called.

I think there is a way to use context management to deal with this, but I don't really understand how they work (so I don't know what I should do with a context manager here).

Boiling down to a question: what do we do here? Is there single desired behavior (run forever  or stop on quit) that we can implement with `QProcess` vs `subprocess`, or do we figure out context management/garbage collection?

### Feedback on the power interface
How does it look? What to add?

### CODE REVIEW

**Comment by KriSun95** [comment]
My worry with the quitting behaviour is if something goes wrong with the GSE then this will, but shouldn't, destroy the data taking process. A power interruption or accidental closure of the GUI, however unlikely, doesn't seem like something to ignore. 

This makes me think the behaviour, if one of the options has to be chosen, should be to "run forever", although this might only kick the can down the road to the next problem of reconnecting to `Listener` if the GSE needs to be/is closed and is started back up...

Another option could be to separate the logging of commands and sending of commands. Then the logging could run forever (and who would car about that), but the sending commands interface could then probably be stopped and started with the GUI as is needed. This sounds OK initially but might/will very likely be much more complicated.

[Context managers](https://book.pythontips.com/en/latest/context_managers.html) are simple enough to get working but I'm unsure how it would help. They rely on creating the magic methods of `__enter__()` and `__exit__()` in the class, which is really simple, but is more of a failsafe as far as I understand it. E.g., instead of always having to close an (e.g.) file manually every time you open one, the context manager will run the code in `__enter__()`, do the stuff there and then call `__exit__()` when the class is done. However, I think you could always just run the `__exit__()` code manually with every use even though that's cumbersome.

**Comment by thanasipantazides** [comment]
To do note to self: power parser currently assumes 5 V rail is exactly 5.0 V. This adds error to current measurements. A better design for `adcparser()` is to first check the measurement of the 5 V channel, then use that value to compute the currents:
```python
raw_5v_bytes = int(bytes_to_parse[6:7], 16)
meas_5v_voltage = 5.0 * (raw_5v_bytes & 0x0fff) / 0x0fff
# ...
channel_current = meas_5v_voltage * (raw_channel_voltage - meas_5v_voltage / 2)
```

Note that the 5.0 coefficient in computing `meas_5v_voltage` is still accurate because the full range is set by $2\times$ `REF_IN`, with `REF_IN` being provided by a clean, regulated 2.5 V source.

**Comment by thanasipantazides** [comment]
Another to do note: the GUI interface to `Listener` should have a `refresh` button that kills the running `Listener` and restarts it, for use in testing when taking long log files. Disable the button during `flight` mode.

**Comment by thanasipantazides** [comment]
Another to do: switch `PowerMonitorView` text fields to use Kris's color-coding widget (see #22 ).

**Comment by thanasipantazides** [comment]
`Listener` should rollingly estimate downlink data rate.

**Pull request merged**
